### ISSUE TITLE
Documentação incorreta de Minimum Deployment Target de iOS para `face_authenticator`

### ISSUE THREAD

**Issue by italotabatinga** [combateafraude/Flutter#32]
Olá!

Parece que o Minimum Deployment Target do `face_authenticator` iOS da documentação está diferente do real. 

Quando tento `pod install` com `platform :ios, '11.0'`, recebo o erro abaixo:
```
Specs satisfying the `face_authenticator (from `.symlinks/plugins/face_authenticator/ios`)` dependency were found, but they required a higher minimum deployment target.
```

Olhando os arquivos, no [podspec do ios](https://github.com/combateafraude/Flutter/blob/face-authenticator/ios/face_authenticator.podspec) está com 12 (adicionado nesse [commit](https://github.com/combateafraude/Flutter/commit/9f681f66ae243b315508c11b5886eea5552fbf93), a documentacao tava 12.0 também), nesse commit a documentação foi alterada de 12.0 para 11.0 (esse [commit](https://github.com/combateafraude/Flutter/commit/607576082945697f5f7f54d0845d2800e233cd3f))

**Comment by murilofank** [comment]
Ajustado o arquivo podspec com `platform :ios, '11.0'`
