### ISSUE TITLE
Adicionar Pigeon para se comunicar com os módulos nativos

### ISSUE THREAD

**Issue by ricardodalarme** [combateafraude/Flutter#49]
## Descrição

Olá, estava analisando o código de vocês e vi que toda a comunicação entre o Flutter e os módulos nativos são feitos a mão, então deixo uma sugestão de utilizarem o Pigeon para simplificar e deixar essa comunicação de uma forma mais type-safe (: 

- https://pub.dev/packages/pigeon

**Comment by bhmsantoscaf** [comment]
Oi @ricardodalarme, somos uma empresa de segurança e termos certas restrições sobre frameworks de terceiros (inclusive code generator). O Pigeon ainda não esta homologado internamente, mas já estamos trabalhando para isso. 

Obrigado pela sugestão!

**Comment by ricardodalarme** [comment]
Vale deixar claro que o pigeon é do próprio Flutter, inclusive é a recomendação de como desenvolver plugins na documentação oficial:

- https://docs.flutter.dev/platform-integration/platform-channels#pigeon

**Comment by bhmsantoscaf** [comment]
@ricardodalarme, sim temos essa visibilidade. Nosso código é nativo e as bridges são tratadas em um fluxo apartado. Mesmo sendo ferramenta do Flutter, precisamos homologar. 

Obrigado novamente.
